# Generated by Django 5.2.5 on 2025-08-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('nota1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nota2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nota3', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
