# Generated by Django 4.2.23 on 2025-08-24 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alumno',
            table='alumnos',
        ),
    ]
